project:
  type: website

website:
  title: "Childhood Overweight Report"

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    code-fold: true

execute:
  echo: true
render:
  - report.ipynb
